name: Update PEP8 Strings

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  schedule:
    - cron: '0 */12 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Config Transifex client
        run: |
          tx init --token=${{ secrets.TRANSIFEX_TOKEN }} --force --no-interactive
          tx config mapping -r persian-pep8.build-gettext-index-pot--main --source-lang en --type PO --source-file _build/gettext/index.pot --expression 'locale/<lang>/LC_MESSAGES/index.po' --minimum-perc 1 --execute

      - name: Get new PEP8 strings and push to Transifex
        run: |
          chmod +x ./update_translations_catalogue.sh
          ./update_translations_catalogue.sh
      
      - name: Commit files to the repo
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Auto update pep8 strings'
          branch: main
          file_pattern: _build/gettext/index.pot
          status_options: '--untracked-files=no'
